#!/bin/bash

echo "🔧 Setting up Supabase Edge Function Secrets..."
echo ""
echo "Please follow these steps in your Supabase Dashboard:"
echo ""
echo "1. Go to: https://supabase.com/dashboard/project/meajkczkzuzksulauprv/settings/functions"
echo "2. Click on 'Secrets' tab"
echo "3. Add these secrets:"
echo ""
echo "   Secret 1:"
echo "   Name: SUPABASE_URL"
echo "   Value: https://meajkczkzuzksulauprv.supabase.co"
echo ""
echo "   Secret 2:"
echo "   Name: SUPABASE_SERVICE_ROLE"
echo "   Value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1lYWprY3prenV6a3N1bGF1cHJ2Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MjY1NDM1MCwiZXhwIjoyMDc4MjMwMzUwfQ.xgao_1lFrGyW7pWDYNVbHyI-BVD5DxKfex0jtwWSMNA"
echo ""
echo "   Secret 3:"
echo "   Name: NASA_API_KEY"
echo "   Value: DEMO_KEY"
echo ""
echo "4. After adding secrets, run:"
echo "   supabase functions deploy mission --project-ref meajkczkzuzksulauprv"
echo ""
